language: node_js

node_js:
  - 0.12
  - 4.3
  - 5

addons:
  firefox: "latest"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - npm run coverage

addons:
  code_climate:
    repo_token:
      secure: "RKrP1qAN0jYSQt8DPgOlAzlb+sqjUZHGZJOAEVNqeblX3HhDXndXCftXdwoL1Sl1EGtygR7XBF3QFur6IXQIQxbOut673Ydyo1+6sulTaD2uSvmzB8E7AXGbjVUSfZ2z8SJ3KNKir4sBgxZJe+XK1kF2vaXLjQQYmehvy2aYr/37yaUfEEZV+E4lV+LyKuWtuc90H3iwiEZfILwtDqA0vGPP5BGJk6XPGeQI2Qwco/iiCKbqlSnPeiShLgaTTX+6yvEUQp0dU+HB0XT+zIg7ZpuTLBsvUM3O8tlHb2D0TegGy+32yMXs23bl7x5fr3MwX5qXzVX68A4WoU8zHnoJxDfXBkX0e6Md6K13/gOtZk080PvFuSqXgkYmM30ZkYqZllnbhaL4FrAWJqkJDyo0c7dM8Kww1FFgbvF/dhl4GUfdleCJi7/fazaojFudBpLU6JFOecbhjNmlxwPr3NL3BLo9IG5frtDebDZj1gZdWtVPUcr/8+3c6xHQBF2C/QQ9gOIPt8DaRmj/vBSNqM5GSA6MPoGcE4mR2zUmo1PUZ2nmfWhZqReY5wQYH17KgrG6vj8SQL1JjfXot3ac1y7i0+oRY2xT06584tTgIQnuy1WL6KWHHEtt2QwFoxOExSfOukTBZy5DR3uc9xMSU9e/FdUjeIPzWmml7DSa+23w9K0="
